### PR TITLE
RA-958 Built module for OpenMRS 2.0 Platform

### PR DESCRIPTION
**Pull request by jdegraft**

### CODE REVIEW

**Comment by dkayiwa** [comment]
After all these changes, does the same module still run well on lower versions of the platform?

**Comment by jdegraft** [comment]
Well, I am not sure how to make the module backwards compatible.
Even the tests which just loads the context fails because the new version of the module uses Java 1.8.
Also I don't know if the name of the package of a class is part of the name. When the allargyapi classes were moved into core, the package names changed. If in bytecode, class names include the package then this will be another major source of backwards incompatibility.

**Comment by dkayiwa** [comment]
Did you get a chance to look at this? https://wiki.openmrs.org/display/docs/Supporting+different+OpenMRS+versions

**Comment by lluismf** [comment]
That's really hacky. It's used abundantly in REST WS with multiple versions
of resources (1.8, 1.9, 1.10...).

2015-11-13 13:17 GMT+01:00 dkayiwa <notifications@github.com>:

**Pull request closed without merging**
